### PR TITLE
Use "base" version of hyperspy and pyfai

### PR DESCRIPTION
**Pull request by ericpre**
to avoid forcing installing optional dependencies.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dnjohnstone** [comment]
Thanks @ericpre - yeah we should probably do this, I think the failing test can probably just be removed directly, but that will require a pyxem-0.12.2 release, which we will do unless @pc494 has a reason why we shouldn't.

**Comment by ericpre** [comment]
An alternative is not to run the test suite in this PR, fix the failing tests in pyxem and re-enable running the test suite in the feedstock for the next release. This would be more simple and avoid installing optional dependencies in the mean time.

**Comment by pc494** [comment]
Is the failing test not caused by us no longer installing an "optional" dependency? Think we could fix that; in a 0.12.2 as @dnjohnstone suggests

**Comment by ericpre** [comment]
As it can be seen, the test suite is failing because the `qt` and the `ipywidgets` packages are not installed anymore which is exactly the purpose of this PR. pxyem runs fine without these expect one(?) GUI functionality and release, which will fixed the test by removing it, isn't necessary.

**Comment by pc494** [comment]
> As it can be seen, the test suite is failing because the `qt` and the `ipywidgets` packages are not installed anymore which is exactly the purpose of this PR. pxyem runs fine without these expect one(?) GUI functionality and release, which will fixed the test by removing it, isn't necessary.

I am not happy that this PR causes us to ship a package with code that will not work when a user runs it. If we consider this functionality "optional" for pyxem then pyxem, at source, should be adjusted accordingly.

**Comment by ericpre** [comment]
> > As it can be seen, the test suite is failing because the `qt` and the `ipywidgets` packages are not installed anymore which is exactly the purpose of this PR. pxyem runs fine without these expect one(?) GUI functionality and release, which will fixed the test by removing it, isn't necessary.
> 
> I am not happy that this PR causes us to ship a package with code that will not work when a user runs it. If we consider this functionality "optional" for pyxem then pyxem, at source, should be adjusted accordingly.

But other users are forced to install stack of libraries which are unnecessary. How is it going to be fixed in pyxem?

**Comment by pc494** [comment]
This was wrapped into version 0.12.2

**Pull request closed without merging**
